[project]
name = "pixabay-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "fastmcp",
    "requests",
    "pydantic",
    "python-dotenv",
]
